### ISSUE TITLE
Add in-browser filesystem browser for single_user_mode

### ISSUE THREAD

**Issue by embray** [jiffyclub/snakeviz#1]
I added a single_user_mode in 91413da that's specifically for a single user running the webserver on their local desktop, and it has very different security assumptions, for example allowing arbitrary files on the filesystem to be opened.  This being the case, we can also build in a file browser to make it easy to switch between profile files in a directory.

Obviously this is not high priority, but it could be nice.

**Comment by jiffyclub** [comment]
Added directory listings in 6e275a9, but I don't think `single_user_mode` is a thing anymore, so folks should be careful opening up snakeviz to others on remote computers. One thing to note, though, is that snakeviz doesn't arbitrarily show the contents of files, it still checks that a file is a readable profile and shows an error if it's not.
