### ISSUE TITLE
Make snakeviz module executable

### ISSUE THREAD

**Issue by orlp** [jiffyclub/snakeviz#101]
If you make a `snakeviz.__main__` module then instead of having to make sure `snakeviz` is in the PATH and uses the right version of Python, we can simply always rely on `python -m snakeviz` instead.

Many packages support this, and it's really convenient, e.g. `python -m pip`.

**Comment by ryanpeach** [comment]
Alternatively, I have made a little bash script for using it, if anyone is interested

```
#!/bin/bash

OUT=`basename $1 .py`
python -m cProfile -o $OUT $1 ${@:2}
snakeviz $OUT
```

**Comment by jiffyclub** [comment]
This seems to work already with the `cli` module, e.g. `python -m snakeviz.cli s3.cprof` can be used interchangeably with `snakeviz s3.cprof`. Does that work like what you had in mind?

**Comment by orlp** [comment]
@jiffyclub  Not yet on the version from pypy (0.4.2). Either way, yes that's what I had in mind but it's a lot more intuitive for users to just be able to use `python -m snakeviz`.

I added a (tiny) pull request that simply makes `python -m snakeviz` work as expected.

**Comment by bary12** [comment]
@jiffyclub when executing `python -m snakeviz.cli` it always writes nothing no matter what arguments I give it.
