### ISSUE TITLE
support for Python 3 profiles

### ISSUE THREAD

**Issue by nschloe** [jiffyclub/snakeviz#103]
Right now, when trying to load Python 3 profiles generated with
```
python3 -m cProfile -o my_program.prof my_program.py
```
with snakeviz (e.g. [this one](https://github.com/jiffyclub/snakeviz/files/1503971/program.zip)), one gets the error message
```
Usage: snakeviz [options] filename

snakeviz: error: the file /path/to/program.prof is not a valid profile.
Generate profiles using: 

	python -m cProfile -o my_program.prof my_program.py
```

**Comment by jiffyclub** [comment]
I use snakeviz with Python 3 profiles, so the compatibility is there. The version of Python that is running snakeviz needs to be the same as the version that generated the profile. So if a profile was generated by Python 3, snakeviz also needs to be running under Python 3. My suspicion here is that when you are calling `snakeviz` from the command line it is running under Python 2.

**Comment by nschloe** [comment]
Certainly. Perhaps the error message could be clarified? (I suppose that making the profiles readable across versions is not an option?)

**Comment by jiffyclub** [comment]
#76 includes that hint but also contains some other stuff so I haven't merged it yet. Would be good to have!

SnakeViz relies on the standard library `pstats` module to read the profile data and that module isn't cross-version compatible, so snakeviz isn't either.

**Comment by nschloe** [comment]
Alright then, let's close this once #76 has landed.
