### ISSUE TITLE
Directory Template Usage

### ISSUE THREAD

**Issue by deckar01** [jiffyclub/snakeviz#109]
I almost started implementing my own admin UI on top of the snakeviz CLI until I stumbled upon the directory template used in `snakeviz/main.py`. That fit my use case perfectly, but it doesn't seem to be documented.

Should this feature be available through the CLI? Is there anything else that needs to be done for that to be an advertised feature?

**Comment by jiffyclub** [comment]
The directory listing is available via the CLI if you pass a directory as the argument to snakeviz, e.g. `snakeviz .` or `snakeviz path/to/some/directory`. Hope that helps! The snakeviz documentation is definitely in need of updating.
