### ISSUE TITLE
Best view defaults?

### ISSUE THREAD

**Issue by takluyver** [jiffyclub/snakeviz#113]
Thanks for Snakeviz, it's my favourite way to view profiling information.

I'd like to open a discussion about changing the default view settings. Every time I fire up Snakeviz, I make the same four clicks: change style to icicle, change depth to 10. Of course these are somewhat subjective preferences, but I think there are solid reasons to prefer them, and to present them as the default.

* **Icicle view**:
  * Displaying rectangles uses space on a rectangular display more efficiently than displaying concentric rings.
  * Icicle view includes labels (#66), so you can quickly see which function each block represents.
  * The area of a block represents the time spent in that function. Concentric rings with constant width get larger the further they are from the centre, distorting the times they represent.
  * You said you were considering this switch in #85.
* **Depth 10**:
  * Display more information on the available screen space.
  * The default of 5 looks about right for the sunburst display; it looks very sparse for icicles, because they use the rectangular space more efficiently.
  * Of course the optimum here depends on screen size and resolution. I'm typing this on a 24" monitor with 1200 vertical pixels resolution, but I'd go for depth 10 on my 14" laptop screen as well. I wouldn't rule out people viewing it from a phone, but I think it's reasonable to say that the defaults should be based on desktop/laptop use.

Thanks for reading this, whether or not you accept the suggestions. :-)

**Comment by jiffyclub** [comment]
Hi! The default style has been changed to icicle on master, I really need to make a release. I'm also up for changing the default depth, which you'd do here: https://github.com/jiffyclub/snakeviz/blob/1de68c48b3e04fc970d6c3de75e673124079ac07/snakeviz/templates/viz.html#L42.

**Comment by takluyver** [comment]
Thanks! PR coming up for the depth.
