### ISSUE TITLE
Auto save after a set time

### ISSUE THREAD

**Issue by Mradr** [jiffyclub/snakeviz#115]
Is it possible to have it auto save/dump the output information after a given time? If not, is there a way to from within the code? I like the profiling, but having to stop my code to get the output is kind of annoying and I like to profile live if I can instead of waiting every time.

**Comment by jiffyclub** [comment]
You'd have to set it up manually yourself, but I think if you used the [`Profile`](https://docs.python.org/3.7/library/profile.html#profile.Profile) class directly I wonder if you could arrange to have it stop profiling and dump the stats after a set period of time.
