### ISSUE TITLE
FileNotFoundError in Windows

### ISSUE THREAD

**Issue by Arakkun** [jiffyclub/snakeviz#118]
using snakeviz on Windows gives the "FileNotFountError: [Errno 2] No such file or directory" on Windows. The only particularity I can see is that every \ has been substituted with \\ in the file path.

It throws too a "RuntimeError: Could not read" but it's probably derived from not being able to find the file.

**Comment by embray** [comment]
Hi @arakkun, what exactly were the steps you took that resulted in this error, and is there a full traceback you could provide?

**Comment by Arakkun** [comment]
Traceback (most recent call last):
  File "C:\Users\mysti\Anaconda3\lib\site-packages\snakeviz\main.py", line 31, in get
    s = Stats(profile_name)
  File "C:\Users\mysti\Anaconda3\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "C:\Users\mysti\Anaconda3\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "C:\Users\mysti\Anaconda3\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mysti\\TirocinioNeodata\\CIKMCup+Baseline\\CIKMCUP2016_Track1_DCA\\profiling.Result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mysti\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\mysti\Anaconda3\lib\site-packages\snakeviz\main.py", line 33, in get
    raise RuntimeError('Could not read %s.' % profile_name)
RuntimeError: Could not read C:\Users\mysti\TirocinioNeodata\CIKMCup+Baseline\CIKMCUP2016_Track1_DCA\profiling.Result.

**Comment by embray** [comment]
Seems normal to me. Are you sure the path is correct?

**Comment by Arakkun** [comment]
I:
1) move to the directory with the Anaconda prompt(via cd) 
2) write 'snakeviz profiling.Result'
And obtain that error. The path is correct, the problem may be
- how Anaconda Prompt(aka the windows prompt) passess it to Snakeviz
- how Snakeviz is managing that path ( the error may be dependant on the '\\', it may be corrected like that if when "FileNotFoundError: [Errno 2]" it tries to open the same path but with '\' instead ).

**Comment by embray** [comment]
I don't think any of those things are the problem. Rather, it does seem to be failing to unquote_plus the URL somewhere along the line. Try using a path that doesn't have spaces in it.

**Comment by Arakkun** [comment]
The path doesn't have space in it already ( the "path with space" problem is python's so after finding it I started using paths without spaces for python)

**Comment by embray** [comment]
Does it have a `+` in it? Because that's probably confusing the URL unescaping as well.

**Comment by jiffyclub** [comment]
What version of SnakeViz are you using? This sounds similar to an issue I fixed in https://github.com/jiffyclub/snakeviz/commit/6851ee789b774a3d0cef7d901b47eb8320a6377d, which was released in version 1.0.0.

**Comment by jiffyclub** [comment]
I'm going to close this since we haven't heard back, but please feel free to re-open if you're still having this issue on the most recent version of snakeviz (though please also try on master since 9505c88 changed some of the filename handling).
