### ISSUE TITLE
Docs more newbee friendly

### ISSUE THREAD

**Issue by guettli** [jiffyclub/snakeviz#122]
You start like this in the docs:

> If you have generated a profile file called ...
Source: https://jiffyclub.github.io/snakeviz/

If you are a newbee. Then you might not know how to create a profile file.

I think it would help if you explain how to create such a file in one line.

Maybe like this:

You can create a profile file like this:  `python -m cProfile -o program.prof my_script.py`

(thank you for this great tool)

**Comment by jiffyclub** [comment]
Thanks for the note! Instructions on building profiles are there, but slightly down the page: https://jiffyclub.github.io/snakeviz/#generating-profiles

The docs are generally super out of date and in need of some work. 😭
