### ISSUE TITLE
%snakeviz magic lumps everything under builtins.exec

### ISSUE THREAD

**Issue by jeslinmx** [jiffyclub/snakeviz#169]
When I generate a `.prof ` file using `Profile.enable()`, `Profile.disable()`, and `Profile.dump_stats`, I get this nice, detailed breakdown  when I use snakeviz to open the profile dump:

![image](https://user-images.githubusercontent.com/1007894/139073300-97e96cb6-5cc3-4ec8-9365-ed49a7ede39b.png)

(textual details removed with css as this is company internal code)

However, when I instead use the `%%snakeviz` magic to profile the same code, the resultant display looks like this:

![image](https://user-images.githubusercontent.com/1007894/139073624-671ccab1-ee72-436b-84ec-1a29867ed8df.png)

which is decidedly less informative. This seems to be a result of snakeviz invoking `%prun`, which in turn invokes `exec()`, which obscures the inner workings of whatever code I'm running from cProfile.

Is there any known workaround for this?

**Comment by jeslinmx** [comment]
Quick update, this was my bad. Didn't fully understand at the time that I could use the table at the bottom to change the root function and thus expose more of the underlying functions.

**Comment by jiffyclub** [comment]
Thanks for coming back with an update! In case you're not aware you can also click on boxes in the visualization to "zoom in" to different parts of the call stack.
