### ISSUE TITLE
a question about show message info 

### ISSUE THREAD

**Issue by ChunelFeng** [jiffyclub/snakeviz#182]
I want to know what does this part mean?

It seems to be repeat the upper layer。

![image](https://user-images.githubusercontent.com/37905059/198547626-d3b36a55-1443-472e-ab54-c0d13b06b304.png)

```python
import time

def test_func():
  for i in range(0, 10000):
    if 0 == i % 20:
      print("message is {}".format(i))

def sleep_func(i):
  time.sleep(i)

def main():
  test_func()
  sleep_func(0.01)
  print('finish')

if __name__ == '__main__':
  main()
```

```bash
python -m cProfile -o stats.dump test.py
snakeviz stats.dump 
```

notice: 
* snakeviz 2.1.1
* Python 3.10.4

**Comment by jiffyclub** [comment]
It does repeat the upper layer, it's meant to represent the time spent in a function that's _not_ spent calling other functions, only executing code within the function itself. cProfile doesn't track that information explicitly, but it can kind of be inferred by looking at how much time is spent in a function vs how much is spent in the other functions it calls.

Your sample `test_func` calls `print`, which is where most of the time is spent, but there's also time that goes into doing the for-loop, the if-check, the math, and the string formatting, what is what that little extra bar is representing.

**Comment by ChunelFeng** [comment]
thanks for your answer.
very good repo
