### ISSUE TITLE
Drop support for EOL Pythons

### ISSUE THREAD

**Issue by matthewfeickert** [jiffyclub/snakeviz#187]
:wave: Hi @jiffyclub, would you be open to dropping support for EOL Pythons (c.f. PR #186) both in terms of testing in CI and in terms of adding a `python_requires` to `setup.py`. At the time of posting, [Python 3.6 and older are EOL](https://peps.python.org/pep-0494/#lifespan) so this would mean dropping testing for Python 3.6 and older and adding a `python_requires='>=3.7'`.

How do you feel about dropping EOL Pythons?

**Comment by jiffyclub** [comment]
In terms of testing I think it's totally fine to stop testing against Python versions that are not easy to test against. In terms of support, the Python parts of snakeviz are extremely simple so it hasn't been an issue to continue to support older versions. There's just hardly anything going on there, all the interesting bits are in JS. So I'm loathe to make claims about version support when really the code will work on about any Python since 2.7.

**Comment by matthewfeickert** [comment]
Thanks, was just curious. I'm in the camp of 'support what you test' and then as you drop older versions of Python you just bump up your [`requires-python`](https://peps.python.org/pep-0621/#requires-python) so that you don't inadvertently break installation on older releases in the future (by putting up something on PyPI that an older Python will happily install but contains something that it can't use) and people who are on older releases of Python can still happily use older versions of the library. But I also live in a world of trying to support [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) which is much more aggressive. :)

Regardless of when you plan to drop support for older Pythons, there currently isn't a `python_requires` in the project [`setup.py`](https://github.com/jiffyclub/snakeviz/blob/d7a3d3bcb6d1289b93af6c932324e4a8a3e2030c/setup.py) so would you be open to a contribution that explicitly adds one like

```python
python_requires = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*",
```

(this is the state of things tested before PR #186)?

This isn't trying to deprive older Pythons, but to protect them against getting broken releases in the future. I appreciate that as you've pointed out the interesting code is in JS and so the Python should be quite robust, but in the unprobable scenario in which a future version of `tornado` (say `tornado` `v7.0.0`) introduces a breaking change then doing the work to fix that and bump up the 

https://github.com/jiffyclub/snakeviz/blob/d7a3d3bcb6d1289b93af6c932324e4a8a3e2030c/setup.py#L60

would mean that, without a `python_requires` to match, older versions of Python will be told they need to try to install a version of a package that they can't &mdash; `tornado` `v6.2` already requires Python 3.7+ and the [next release will be Python 3.8+](https://github.com/tornadoweb/tornado/blob/0f8e10b9756dfa35b5a2345d0d5d978e1e09dc2b/setup.py#L75) &mdash; and the install will fail.

(For others interested in this, there is a pretty good discussion on the importance of this from the other perspective of avoiding upper limits on `requires-python` at https://discuss.python.org/t/requires-python-upper-limits/12663)

Sorry for the wall of text &mdash; it is late where I am and so I wrote a long response instead of a clear short one. My intent isn't to annoy or make additional requests of you. Thanks very much for your continued maintenance of this nice tool for everyone!

**Comment by jiffyclub** [comment]
Sounds like it'd be useful to add the `python_requires` before updates to the supported versions are made!

**Comment by matthewfeickert** [comment]
> Sounds like it'd be useful to add the `python_requires` before updates to the supported versions are made!

I would agree. Would you be open to a contribution that explicitly adds one like

```python
python_requires = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*",
```

(this is the state of things tested before PR #186)?

**Comment by jiffyclub** [comment]
Works for me!

**Comment by matthewfeickert** [comment]
So for the goals of what I described in https://github.com/jiffyclub/snakeviz/issues/187#issuecomment-1415135684 to be useful, a release containing PR #188 would need to be made to PyPI before any further revisions to the `requires-python` metadata. This would ensure that an older version of CPython that hits the lower bound guards implemented in `requires-python` then is able to backtrack to this release with PR #188 in it.

**Comment by jiffyclub** [comment]
[Release 2.1.2](https://pypi.org/project/snakeviz/2.1.2/) includes the new Python requires metadata. I'm going to update to a `pyproject.toml` setup and I'll drop explicit support for <3.7 as part of that update.

**Comment by jiffyclub** [comment]
Version 2.2.0 is out with `requires-python = ">=3.7"`. Thanks for bringing this up!

**Comment by matthewfeickert** [comment]
> Version 2.2.0 is out with `requires-python = ">=3.7"`. Thanks for bringing this up!

Fantastic! Thanks for this work @jiffyclub. :+1:
