### ISSUE TITLE
subprocesses

### ISSUE THREAD

**Issue by ryandvmartin** [jiffyclub/snakeviz#190]
Hi - this is an excellent little profiling tool. 

I am wondering if it is possible for `snakeviz` to trace into subprocesses that may have been spawned during execution of a cell?

**Comment by jiffyclub** [comment]
Snakeviz isn't doing the actual profiling, it's only a viewer for profile data created by the [`cProfile` module](https://docs.python.org/3/library/profile.html#module-cProfile). If your subprocess is Python code you could potentially manually add profiling to that code (see [example in the docs](https://docs.python.org/3/library/profile.html#profile.Profile), but it wouldn't be profiled along with the other parts of your cell, you'd need to separately launch snakeviz to look at that profile output. If your subprocess is not Python then some other profiling tool would be required and you wouldn't be able to use snakeviz.

**Comment by ryandvmartin** [comment]
Thanks - appreciate the comment, and the link to the example.
