### ISSUE TITLE
How to run SnakeViz?

### ISSUE THREAD

**Issue by tdgrant1** [jiffyclub/snakeviz#23]
I'm a relative noobie to python so I'm missing something simple because I can't seem to run SnakeViz on my Mac (10.8.5, using fink python).

The website says to simply type snakeviz name_of_profile on the command line, but that doesn't seem to work, with the error command not found.  I must be misunderstanding something basic because usually I run python scripts with something like python snakeviz.py name_of_profile, but there doesn't seem to be a snakeviz.py or anything similar that I would be able to call.

I'm pretty sure it's installed correctly because when I enter the python interpreter and type import snakeviz it appears to be successful, I just don't know how to actually invoke the program.

Can you help?

Tom

**Comment by GuidoJH** [comment]
Why is this issue closed? How is this not a bug?

It's late 2016 now and I just installed using pip and I see the same problem.  It is at least a bug in the documentation that says "install with pip, then run snakeviz". It doesn't work that way.

**Comment by GuidoJH** [comment]
I realized what was the problem now. For anyone to whom it may be helpful:

I installed using --user option in pip to avoid using sudo. This didn't install properly, but showed no error messages. To fix it simply uninstall and then install again using sudo.

**Comment by embray** [comment]
@GuidoJH 
> I installed using --user option in pip to avoid using sudo. This didn't install properly, but showed no error messages. To fix it simply uninstall and then install again using sudo.

That sounds like an issue with your configuration (and in general "install using sudo" is poor advice).  You didn't mention what OS you're using, but `pip install --user` typically installs into `$HOME/.local`, and the `snakeviz` executable will be in `$HOME/.local/bin/snakeviz`, so you need to make sure that `$HOME/.local/bin` is on your `$PATH` if you want to use `pip install --user`.  This is true in general for Python packages and is in no way particular to snakeviz.

**Comment by luofanghao** [comment]
I have same issue with MacOS. I installed using pip but then snakeviz cannot be executed from terminal. And under my $HOME/.local/ there is no folder "bin".

**Comment by GoingMyWay** [comment]
@luofanghao 

On MacOS, please check `/Users/USER_NAME/Library/Python/PY_VERSION/bin`

**Comment by GoingMyWay** [comment]
@embray 

I can't agree more, you are right!

**Comment by liuyigh** [comment]
On MacOS with .pyenv, you may have to restart a new shell session for the bin to be seen. FYI.

**Comment by jiffyclub** [comment]
More recent PRs have added the ability to call SnakeViz via `python -m snakeviz name_of_profile`, which won't depend on the snakeviz executable being available.

**Comment by yushuinanrong** [comment]
> I realized what was the problem now. For anyone to whom it may be helpful:
> 
> I installed using --user option in pip to avoid using sudo. This didn't install properly, but showed no error messages. To fix it simply uninstall and then install again using sudo.

You saved my day!

**Comment by korbinianbauer** [comment]
> More recent PRs have added the ability to call SnakeViz via `python -m snakeviz name_of_profile`, which won't depend on the snakeviz executable being available.

Thanks, this did it for me.
