### ISSUE TITLE
Multiple reports displaying support

### ISSUE THREAD

**Issue by dmitry-krasilnikov** [jiffyclub/snakeviz#44]
Hi!
I'm not sure that this is the best place for it. I wanted to make an improvement proposal, it would be really great to be able to view several reports at a time, maybe with some search functionality across the reports. I've bumped into the problem when I'm working with 66 files of profiling data, but maybe I miss some obvious points?

**Comment by jiffyclub** [comment]
Sounds like something similar to the file browser in the IPython Notebook?

**Comment by dmitry-krasilnikov** [comment]
No, it doesn't. I've already written a script which helps me in this case and I can't think of any other cases when multiple opened reports might be needed. So, sorry that I bothered you. Thanks for your tool, it was very helpful indeed!
