### ISSUE TITLE
Browser does not open on Mac

### ISSUE THREAD

**Issue by kakyoism** [jiffyclub/snakeviz#46]
Environment: Macbook Air 2012, OS X 10.8.2, Safari 8.0.3., bash-3.2.57, python 2.7.5 (Mac default), snakeviz-0.2.1

Repro
1. Created a run.prof from cProfile against a test script.
2. Open Terminal on Mac.
3. Type "snakeviz run.prof".

Problem:
See this message hanging forever: "snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit", and nothing happens beyond this.

Expected: Browser (Safari by default) should open and show some eye candies.

**Comment by jiffyclub** [comment]
Can you open a Python interpreter, enter the following, and let me know what happens?

```pycon
>>> import webbrowser
>>> webbrowser.open('http://www.python.org')
```

**Comment by jiffyclub** [comment]
Can you also go to the "General" pane of the System Preferences and check that you have a default web browser set? Here's what mine looks like, but I'm on Yosemite so yours will look somewhat different.

![screenshot 2015-02-15 19 20 28](https://cloud.githubusercontent.com/assets/920492/6206822/ddc24cf8-b547-11e4-97ee-c0b1d24350c5.png)

**Comment by kakyoism** [comment]
<Quote>
>>> import webbrowser
>>> webbrowser.open('http://www.python.org')
<Quote>

This gives me "True".

My default browser is Safari.app

**Comment by kakyoism** [comment]
BTW, the command line does end up opening the python homepage in Safari.

**Comment by jiffyclub** [comment]
Thanks. Here's another experiment for the console, if you don't mind. What's the output of this?

```pycon
>>> import webbrowser
>>> webbrowser.get()
```

And then try:

```pycon
>>> webbrowser.get().open('http://www.python.org')
```

Thanks!

**Comment by kakyoism** [comment]
>>> import webbrowser
>>> webbrowser.get()
<webbrowser.GenericBrowser object at 0x10f55e3d0>
>>> webbrowser.get().open('http://www.python.org')
False
>>>

**Comment by kakyoism** [comment]
>>> import webbrowser
>>> webbrowser.get()
# <webbrowser.GenericBrowser object at 0x10f55e3d0>
>>> webbrowser.get().open('http://www.python.org')
False
>>>

**Comment by kakyoism** [comment]
>>> import webbrowser
>>> webbrowser.get()
webbrowser.GenericBrowser object at 0x10f55e3d0
>>> webbrowser.get().open('http://www.python.org')
False
>>>

**Comment by jiffyclub** [comment]
As you might have guessed, that second way is how snakeviz is trying to open your browser, and that's why you're not ending up with anything happening.

It's really weird that `webbrowser.open()` works and `webbrowser.get().open()` doesn't. I can't reproduce that even if I install Python 2.7.5 and set my default browser to Safari. :(

One thing to try is explicitly specifying a browser to snakeviz using the `-b/--browser` flag. E.g.: `snakeviz -b safari myprofile`.

As a last resort, you can manually copy the URL printed to the terminal by snakeviz (e.g. 127.0.0.1:8080) and paste that into a browser.

Sorry I can't be more help, I'm totally stumped.

**Comment by kakyoism** [comment]
I tried to c&p the address into Safari, and here is what I got:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1323, in _execute
    result = self.prepare()
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 2014, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

Thank you for your patience.

**Comment by jiffyclub** [comment]
I apologize, I gave you some bad advice there. Snakeviz does not print out a complete URL that you can paste into a browser. I'll make an issue to fix that.

Have you tried the `-b` option to manually specify the browser?

**Comment by kakyoism** [comment]
"-b safari" solved the problem. Thanks a lot!
I had thought I ought to use the full path to the executable which would have been /Applications/Safari.app/Contents/MacOS/Safari . This never worked. 

You might consider revising the help text about the -b option.

Again, thanks for the prompt help!

**Comment by jiffyclub** [comment]
Good idea, thanks. I only learned about that trying to figure out how to help you. :smile_cat: You can see a list of all the browsers the `webbrowser` module knows about at https://docs.python.org/3.4/library/webbrowser.html.
