### ISSUE TITLE
Not working through SSH port forwards

### ISSUE THREAD

**Issue by demianw** [jiffyclub/snakeviz#58]
Hi! Thanks for this wonderful tool! I'm using it a lot and many times I don't have direct access to where my files and soft are. So I use port forwarding a lot. However, this doesn't work with snakeviz.

Could it be due to absolute vs relative paths in the web application?

Thanks in advance to check this out and let me know if I can help

**Comment by jiffyclub** [comment]
Can you give a little more detail about how you're trying to start snakeviz? Are you using server-only mode?

**Comment by demianw** [comment]
Hello! I'm in a remote SSH session, using the port forwarding option 
-L 8888:127.0.0.1:8888
And I'm starting snakeviz on that specific port and in server mode. 

Then, I start a browser on my local machine and go to the address 127.0.0.1 port 8888

This works perfectly with other tornado-based web apps such as the ipython notebook

Thanks!
--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée
2004 route des lucioles - FR-06902

**Comment by jiffyclub** [comment]
Do you get a 404, or nothing at all?

You can't go to just the root of the app (e.g. http://127.0.0.1:8888) because there's no handler for that, it will 404. You need to go to the full URL for a specific profile. SnakeViz prints that out when you start it.

**Comment by demianw** [comment]
You're right. That was the problem! Thanks, this is a great tool.

 If you give me a couple pointers, maybe I could help in adding a root handler that just performs redirection. Unless there's a reason not to have a root handler

**Comment by jiffyclub** [comment]
We might want to save the root handler to be a file browser, but I don't have any immediate plans to work on that. One thing the root handler could be for now is a list of known profiles. (You can always change the URL to open a visualization of a different profile than the one you originally started from.) I think the best way to keep that list would be as a Python set in the Tornado application's settings dictionary. The set could be updated every time SnakeViz serves a profile.

If it's something you're interested in we can talk about it more, but no rush or pressure.
