### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by JPFrancoia** [jiffyclub/snakeviz#61]
Hi,

Just a quick question because I'm really interested by snakeviz. Is it possible to profile memory usage with snakeviz ? Runsnakerun could do it with meliae.

Thanks !

**Comment by embray** [comment]
Not currently.  I don't think it would be significantly hard to do though; it would just need to be able to read memory profiler results.

**Comment by Sourabh-DSA** [comment]
Do we have this functionality now? Can we plot memory profiles in snakeviz?
