### ISSUE TITLE
sections are incorrectly ordered, proportioned

### ISSUE THREAD

**Issue by nschloe** [jiffyclub/snakeviz#72]
I noticed that sometimes, the sections in both Sunburst and Icicle view are incorrectly proportioned. Take the output from [this profile](http://chunk.io/f/2ac5ae5ab9ac47e5b206d12b9276212e):
![sc](https://cloud.githubusercontent.com/assets/181628/16961140/7d5cfe3c-4dec-11e6-902a-0b80281319fd.png)
The highlighted `multilevel.py` section has over 50% compute time, but doesn't stretch over 50% of the entire width, and in fact is not even leftmost.

**Comment by nschloe** [comment]
I've looked into snakeviz's code a little bit, played around with some profiles and found that this is most likely a D3 issue. The `size`s are all set correctly, but the `dx` values generated by `d3.layout.partition()` are wrong. This hasn't changed in 3.5.17, their latest release in the 3 series. I suppose an update to 4.* is warranted then.

**Comment by jiffyclub** [comment]
Thanks for investigating! I've occasionally noticed this also, but have had a hard time deliberately generating test profiles that exhibit this problem. Do you have a profile you can share that shows this that I can use as a test case?

**Comment by jiffyclub** [comment]
Oh nevermind, I see your link above. Thanks!

**Comment by nschloe** [comment]
From what I've understood, d3 disregards all `size` entries _except_ the ones in the leaves, and adds them up to construct the `size`s for the parents. That explains why in [`.value()`](https://github.com/jiffyclub/snakeviz/blob/master/snakeviz/static/drawsvg.js#L41) I never see nodes with `"children"`.

Now, the data you get from the performance measurement is structured a little bit differently in that every node is associated with a time. It looks like the function [`sv_build_hierarchy`](https://github.com/jiffyclub/snakeviz/blob/master/snakeviz/templates/viz.html#L134) is built to bridge the gap between input and D3 data. An interesting bit is [the part where it adds a node](https://github.com/jiffyclub/snakeviz/blob/master/snakeviz/templates/viz.html#L204) to account for a parent time (size) that's not covered by its children.

I don't quite unterstand why this part is so complicated though: Replacing
```
              size: Math.max(
                0, (parent_time - time_in_children) / parent_time * node_size)
```
by
```
size: node_size - size_of_children
```
looks correct and more natural. Not that it fixes the issue though.

**Comment by nschloe** [comment]
Comments like
```
          // if the children add up to be larger than the parent
          // then normalize them to the parent size
```
make me think that something is fishy.

**Comment by jiffyclub** [comment]
Yeah, that is a hack that I think is necessary because the profiling data doesn't always make clear how much time was spent in a function _in a particular part of the call graph_. For example, if funcA calls funcB and funcB calls funcC and funcC takes 1 second, then in another place funcZ calls funcB and funcB calls funcC and funC takes 10 seconds, all we know from the profile data is that funcC spent 11 seconds running under funcB. We don't know how much of that time was spent under funcA or funcZ. So you have to make sure child nodes don't outgrow their parents in situations like that. (My memory could be imperfect here, or I could be completely wrong, but this is the justification I recall for having to do that.)

**Comment by nschloe** [comment]
Hm, sounds tricky.

Anyhow, PR #79 fixes the issue for me.

**Comment by nschloe** [comment]
Now that #79 has been merged, this can be closed.
