### ISSUE TITLE
invalid profile error

### ISSUE THREAD

**Issue by imranashraf** [jiffyclub/snakeviz#78]
I am generating a profile using the command `python -m cProfile -o my_program.prof my_program.py` on Ubuntu 16.04. However, I get the following error when i try to run snakeviz:

```
snakeviz program.prof 

Usage: snakeviz [options] filename

snakeviz: error: the file /data/repositories/quantRepos/sc_decoding/program.prof is not a valid profile. Generate profiles using: 

	python -m cProfile -o my_program.prof my_program.py
```

What am I doing wrong?

**Comment by embray** [comment]
Chances are you're running snakeviz installed with Python 3 on a profile generated from Python 2 or vice-versa.  The profile formats between python 2 and 3 are incompatible, and IIRC snakeviz can't read cross-version profiles still.

**Comment by tisdall** [comment]
It would be nice if the explanation given here was included in that error message!

**Comment by jiffyclub** [comment]
#76 actually adds that hint, but we haven't merged it yet because I don't think we've tested the tox aspect of the PR.

**Comment by Yenthe666** [comment]
This issue is still relevant to today. When a profile is generated from a Python 3 environment and you try to open it with Python 2 you'll get this traceback while the error message is completely wrong.
Any chance this can be added in the warning with a check?
