### ISSUE TITLE
explicit value for box width relative to immediate parent

### ISSUE THREAD

**Issue by astooke** [jiffyclub/snakeviz#80]
Hi,

 First of all...thanks for snakeviz, it's super helpful!

The one feature I find myself looking for over and over is to see an explicit value which relates the width of a box (thinking icicle mode) to it's parent, rather than just the total time across the program.  @jiffyclub you hinted at this in a comment in #72.  It could be in units of seconds or a percentage.  It seems like this value must already be available somewhere, to render the boxes, but it's not presented anywhere in the GUI?

**Comment by jiffyclub** [comment]
Unfortunately this information is not available in the profile data, I wish it was. 😞 When a function is called multiple times in different parts of the call tree its size relative to parents is basically fudged and can be in inaccurate. See #112 for an example.
