### ISSUE TITLE
snakeviz does not work on "regular" profile?

### ISSUE THREAD

**Issue by eteq** [jiffyclub/snakeviz#84]
I noticed some curious behavior today.  If I do:
```
python -m cProfile -o test.prof test.py
snakeviz test.prof
```
snakeviz works as expected.  But If I do 
```
python -m profile -o test.prof test.py
snakeviz test.prof
```
I get a traceback instead of the proper output (traceback at the bottom).  Is this an upstream Python problem? I.e., the `.prof` files are supposed to be drop-in compliant, right?

```
Traceback (most recent call last):
  File "/.../lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/.../lib/python3.5/site-packages/snakeviz/main.py", line 33, in get
    table_rows=table_rows(s), callees=json_stats(s))
  File "/.../lib/python3.5/site-packages/snakeviz/stats.py", line 62, in json_stats
    (keyfmt(*ck), list(cv)) for ck, cv in v.items())
  File "/.../lib/python3.5/site-packages/snakeviz/stats.py", line 62, in <genexpr>
    (keyfmt(*ck), list(cv)) for ck, cv in v.items())
TypeError: 'int' object is not iterable
```

**Comment by jiffyclub** [comment]
This is a known issue, see #60, #63. I don't remember the exact details anymore but I think there are indeed differences in the profiles generated by `profile` and `cProfile` that make it so I can't extract the necessary info for SnakeViz from `profile` profiles (at least, obviously, it can't be done in the same way).

**Comment by embray** [comment]
My guess is it's an upstream Python bug.  Surprising that it's one that still lives on in Python 3.5 though.
