### ISSUE TITLE
Snakeviz cannot launch browser on mac OS 10.12.5 

### ISSUE THREAD

**Issue by prashantmital** [jiffyclub/snakeviz#87]
Attempting to open profile files using the `snakeviz` entry-point no longer opens an instance of the default browser:

```
$ snakeviz basic_profile.prof &
[1] 11150
[username:~/work] $ snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2FUsers%2Fusername%2Fwork%2Fbasic_profile.prof
0:163: execution error: "http://127.0.0.1:8080/snakeviz/%2FUsers%2Fusername%2Fwork%2Fbasic_profile.prof" doesn’t understand the “open location” message. (-1708)
```

It appears that this bug was introduced in 10.12.5 which I updated to recently as I didn't have the problem prior to the update.

**Comment by prashantmital** [comment]
The issue has actually been pretty well researched at this point, and boils down to a bug in `osascript` which is used to open the browser. 

There is a detailed discussion of it here:
https://github.com/fish-shell/fish-shell/issues/4035

**Comment by jiffyclub** [comment]
Thanks for the report! Hopefully the next macOS release will have the fix and be out soon.

**Comment by prashantmital** [comment]
I am saving profile files to disk using `cprofile.dump_stats` and then using the `snakeviz` entrypoint to open them as you suggest. How is that different from using `%prun`?

**Comment by prashantmital** [comment]
It appears that `%prun` might be using `profile` instead of `cProfile`?

**Comment by jiffyclub** [comment]
That's effectively the same workflow @prashantmital. `%prun` is a way to do it in the notebook (so you can replace `%snakeviz` with `%prun` in the same cell). I think `%prun` is using `cProfile` (unless there have been recent changes) because under the hood the `%snakeviz` magic is calling the `%prun` magic code. Are you seeing it not work?

**Comment by prashantmital** [comment]
Yeah I can see it not work when I do `snakeviz profile_file` from the CLI. I get the same error I mentioned in the OP.

**Comment by jiffyclub** [comment]
Same, I tried this out today. If you do `snakeviz --server profile_file` you'll avoid the error and it'll print out a URL you can copy and paste into your browser. Hope we don't have to live like this forever!

**Comment by prashantmital** [comment]
Nifty! Thanks for that tip.

I think this might be related (but not sure). I often log into remote machines where profile files are stored. Currently, I `scp` the files back to my local machine and then open them using `snakeviz`, but I was wondering if there could be a way to spawn the `snakeviz` server on the remote machine and look at it using my local web browser? Might be more of a networking question than anything, but wondering if you know anything about that.

**Comment by prashantmital** [comment]
Never mind, figure it out! There is some chatter on https://github.com/jiffyclub/snakeviz/issues/58 that helped. 

This is a great project, thanks for maintaining it.

**Comment by jiffyclub** [comment]
Glad you're finding snakeviz useful! Feel free to share how you got the remote server working, other folks might find it interesting.

**Comment by prashantmital** [comment]
Here is a copy of the instructions I wrote up for my own future reference: 

First start the `snakeviz` server on the remote on a particular port:
```
$ snakeviz --server --port 8888 profile_file
```
OR
```
$ snakeviz -s -p 8888 profile_file
```

Note the URL that `snakeviz` spits out. Let's say for this example that the path is:
```
http://127.0.0.1:8888/snakeviz/%2Fhome%2Fsnail%2Fanalysis_results%2F14workers_master%2F_main.prof
```

Now, set up port forwarding in a separate SSH session with the remote. Use the IP of the `snakeviz` server from the previous step as the target:
```
$ ssh -L 8080:127.0.0.1:8888 username@servername
```

This forwards connections on the host to `localhost:8080` to `127.0.0.1:8888` on the remote.  The user can Therefore to see the `snakeviz` output, the user can visit:
```
http://localhost:8080/snakeviz/%2Fhome%2Fsnail%2Fanalysis_results%2F14workers_master%2F_main.prof
```
