### ISSUE TITLE
snakeviz not working in jupyter notebook

### ISSUE THREAD

**Issue by flothesof** [jiffyclub/snakeviz#88]
Hi,
I've just learned about snakeviz and trying to make it work inside the notebook (Python 3.6, notebook 5.0).

Here's my testcase:

```python
def pi_approximate(n):
    step = 1.0 / n
    result = 0   
    for i in range(n):
        x = (i + 0.5) * step
        result += 4.0 / (1.0 + x * x)
    return step * result
%load_ext snakeviz
%snakeviz pi_approximate(1000000)
```
I expected this to embed the visualization inside the notebook. However, all I get is this message: 
`*** Profile stats marshalled to file '/var/folders/r9/s1k2nd110xzfxyfym7jmyb8r0000gn/T/tmp9w2usfaj'. `

Could you tell me what I'm doing wrong?

Thanks for your work,
Florian

**Comment by jiffyclub** [comment]
The expected result is not that it embeds anything in the notebook, rather it's expected to open the snakeviz visualization in a new tab. But it sounds like that might not be happening either or you'd likely have noticed. Is there any output in the console when you do this? If there was an exception it might show up there.

**Comment by flothesof** [comment]
Hi @jiffyclub 
I just tried this again and you were right, there's something in the console.
```
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2Fvar%2Ffolders%2Fr9%2Fs1k2nd110xzfxyfym7jmyb8r0000gn%2FT%2Ftmpytz_362p
0:119: execution error: "http://127.0.0.1:8080/snakeviz/%2Fvar%2Ffolders%2Fr9%2Fs1k2nd110xzfxyfym7jmyb8r0000gn%2FT%2Ftmpytz_362p" doesn’t understand the “open location” message. (-1708)
```
I've seen this come up a couple of times in the last weeks: I think it's related to the latest OSX update.
In particular, this behaviour is also showing with the Jupyter notebook. See https://github.com/jupyter/notebook/issues/2438 for a similar error message.

Guess I can only blame Apple for this... 
Thanks for your time,
Best regards,
Florian

**Comment by jiffyclub** [comment]
Ah, that's right. This was reported a little bit ago #87 but I forgot about it.

**Comment by jiffyclub** [comment]
Cross posting from #87: A workaround for this issue is to use the [`%prun` magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-prun) to save a profile file to disk and then open it in snakeviz via the CLI: `snakeviz profile_file`.

**Comment by jiffyclub** [comment]
I think this has been fixed in a recent OS X update.
