### ISSUE TITLE
Tarball generated on PyPi has incorrect permissions

### ISSUE THREAD

**Issue by thrasibule** [jiffyclub/snakeviz#92]
This is what I see inside the tarball:
-rw-r----- jiffyclub/staff  15128 2014-10-15 01:02 snakeviz-0.4.1/snakeviz/static/vendor/jquery.dataTables.min.css
-rw-r----- jiffyclub/staff  78480 2014-10-15 01:01 snakeviz-0.4.1/snakeviz/static/vendor/jquery.dataTables.min.js
 and 
-rw-r----- jiffyclub/staff  1118 2014-10-15 01:48 snakeviz-0.4.1/snakeviz/static/images/sort_asc.png
-rw-r----- jiffyclub/staff  1136 2014-10-15 01:48 snakeviz-0.4.1/snakeviz/static/images/sort_both.png
-rw-r----- jiffyclub/staff  1127 2014-10-15 01:48 snakeviz-0.4.1/snakeviz/static/images/sort_desc.png
These files don't have the read permission for other, so they're not accessible when I run snakeviz. I'm not sure how the permissions got changed since they're correct in the git repo, and the archive files on github are correct.

**Comment by jiffyclub** [comment]
I just made a new release and it looks like the files are readable by all in the .zip source package. Thanks for the report and let me know if you observe any other strangeness.
