### ISSUE TITLE
It'd be nice to print the output of `-h` when snakeviz fails to start.

### ISSUE THREAD

**Issue by fake-name** [jiffyclub/snakeviz#96]
I basically exclusively use snakeviz on headless systems, so basically every startup turns into having to read the help output for how to make it do anything..

Now, it seems to me that the optimal solution would be for snakeviz to check if a browser is present, and if not basically assume `-s -H 0.0.0.0`, but that might be a bit much. 

I think at minimum it'd probably be good to print the output from the `-h` command if snakeviz fails to start.

**Comment by jiffyclub** [comment]
I think we could use [`OptionParser.get_usage()`](https://docs.python.org/3.6/library/optparse.html#optparse.OptionParser.get_usage) to include the usage output with all the error messages.

Since SnakeViz no longer officially supports Python 2.6, we could also think about switching to the `argparse` module.

**Comment by fake-name** [comment]
It should be noted: This is a really, **really** minor quibble.

**Comment by jiffyclub** [comment]
With a switch to argparse errors now produce output like 

```
> snakeviz s3.cprof -L 0.0.0.0
usage: snakeviz [-h] [-H ADDR] [-p PORT] [-b PATH] [-s] filename
snakeviz: error: unrecognized arguments: -L 0.0.0.0
```

and 

```
> snakeviz asdf
usage: snakeviz [-h] [-H ADDR] [-p PORT] [-b BROWSER_PATH] [-s] filename
snakeviz: error: the file /Users/stuff/snakeviz-profs/asdf does not exist
```

That's not the full help, but it at least lists out the different options (which it did not before). Is that helpful?

**Comment by fake-name** [comment]
Hmm, it's too bad there's no way to attach a callback that executes when argparse encounters an error

**Comment by jiffyclub** [comment]
Nice find, with a subclass I can get the error message reformatted as

```
> snakeviz s3.cprof -L 0.0.0.0
snakeviz: error: unrecognized arguments: -L 0.0.0.0

usage: snakeviz [-h] [-H ADDR] [-p PORT] [-b BROWSER_PATH] [-s] filename

Start SnakeViz to view a Python profile.

positional arguments:
  filename              Python profile to view

optional arguments:
  -h, --help            show this help message and exit
  -H ADDR, --hostname ADDR
                        hostname to bind to (default: 127.0.0.1)
  -p PORT, --port PORT  port to bind to; if this port is already in use a free
                        port will be selected automatically (default: 8080)
  -b BROWSER_PATH, --browser BROWSER_PATH
                        name of webbrowser to launch as described in the
                        documentation of Python's webbrowser module:
                        https://docs.python.org/3/library/webbrowser.html
  -s, --server          start SnakeViz in server-only mode--no attempt will be
                        made to open a browser
```

**Comment by fake-name** [comment]
Fancypants! 

Maybe one more idea would be a single arg that implies bind 0.0.0.0, but that's opinion based too.

**Comment by embray** [comment]
> Maybe one more idea would be a single arg that implies bind 0.0.0.0, but that's opinion based too.

Not a great idea. In most cases one should never bind a server to 0.0.0.0 unless you really mean it--a single flag for that makes it too easy to do accidentally.

**Comment by fake-name** [comment]
@embray - I've never been in a context using snakeviz where I *didn't* wind up needing to `bind 0.0.0.0`, because none of the systems I ever develop on have a UI, and I'm working over SSH. I suspect this is more of a "different people's use-case" thing then a general statement you can make.

**Comment by embray** [comment]
Hence "in most cases".  You're talking about an unusual situation.  I don't think you'll find many programs that have a shortcut to bind to 0.0.0.0
